### ISSUE TITLE
Tinkers EFLN explodes borders of claims

### ISSUE THREAD

**Issue by clienthax** [MinecraftPortCentral/GriefPrevention#707]
Does nothing when fired from inside claim, but standing outside claim and firing it at the border destroys blocks inside the claim

possiblyt related to
https://github.com/SpongePowered/SpongeForge/issues/1209

https://griefprevention.github.io/debug/?whbySGUiN2

**Comment by bloodmc** [comment]
This may be related to the Quark bug, can you test latest GP and report back?

**Comment by clienthax** [comment]
Same behaviour
https://griefprevention.github.io/debug/?GBi4wlKj0R

**Comment by bloodmc** [comment]
This is an issue on SpongeForge that I'll have to fix.

**Comment by bloodmc** [comment]
@clienthax Please test latest SF and GP.

**Comment by bloodmc** [comment]
Looks like there was a bug in tinkers as well which was fixed recently.

https://github.com/SlimeKnights/TinkersConstruct/issues/3502

Make sure to test with latest TinkersConstruct.

**Comment by JoeSGT** [comment]
still an issue and my versions are 

GP: 1.12.2-4.3.0.662
SF: 1.12.2-2768-7.1.2
LP: 4.3.11
TConstruct: 1.12.2-2.11.0.106
