### ISSUE TITLE
Sponge and GP: Villager duplication bug

### ISSUE THREAD

**Issue by ResponsibleBear** [MinecraftPortCentral/GriefPrevention#726]
Hello. Here is video!
https://youtu.be/zemXHVupDmw

**Comment by bloodmc** [comment]
You need to provide output of `/gpversion` or this is useless.

**Comment by ResponsibleBear** [comment]
My bad, sorry.
[GP] Running GriefPrevention 1.12.2-4.3.0.644
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3320
[GP] Running luckperms 4.2.22

**Comment by bloodmc** [comment]
I can't seem to reproduce this. Please list exact steps on how to reproduce.

**Comment by ResponsibleBear** [comment]
1. Find or summon Farmer Villager.
2. Find or maker beds with wheat.
3. Make basic claim.
4. Profit.
The rest is shown on the video. 
The farmer breaks the wheat, the player takes it. This goes on forever.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/8680fc21d3a77013e035f572ea559ce21aa35fa7

**Comment by ResponsibleBear** [comment]
Nope not fixed. Here is the video.
https://youtu.be/K3HcBP3z5tE

[GP] Running GriefPrevention 1.12.2-4.3.0.645
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3334
[GP] Running luckperms 4.2.51
