### ISSUE TITLE
Sponge and GP: Wither duplication bug

### ISSUE THREAD

**Issue by ResponsibleBear** [MinecraftPortCentral/GriefPrevention#730]
This is similar to my previous issue, see - MinecraftPortCentral/GriefPrevention#726

We have a basic claim, wither and any other blocks that want to dupe.
In the video, I used the AE system. You can put a chest with resources or diamond blocks that's not important. Summon wither, he begins to break the blocks, they begin to multiply.

Here is  the proof https://youtu.be/xzPJn7hrgh0

Please @bloodmc fix this. Many thanks.

[GP] Running GriefPrevention 1.12.2-4.3.0.644
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3323
[GP] Running luckperms 4.2.51

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/8680fc21d3a77013e035f572ea559ce21aa35fa7

**Comment by ResponsibleBear** [comment]
Nope not fixed.
Now works both in claim and without claim.

https://youtu.be/H9D1Xrk-Drs

[GP] Running GriefPrevention 1.12.2-4.3.0.645
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3334
[GP] Running luckperms 4.2.51
